### ISSUE TITLE
Conflict with CIDER when used as a dev-dependency

### ISSUE THREAD

**Issue by luxbock** [kkinnear/zprint#19]
Hi, I'm not sure which project this issue should belong to so I've filed it in both.

I'd like to use zprint as a dev-dependency, but when I try to do so I run into the following Exception when trying to start a REPL via CIDER:

(when using it as a regular project dependency everything seems to work alright)

```
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: cider.nrepl.middleware.macroexpand/wrap-macroexpand in this context, compiling:(C:\Users\Olli\AppData\Local\Temp\form-init755829693141095127.clj:1:9531)

	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6926)

	at clojure.lang.Compiler.analyze(Compiler.java:6701)

	at clojure.lang.Compiler.analyze(Compiler.java:6657)

	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3835)

	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6921)

	at clojure.lang.Compiler.analyze(Compiler.java:6701)

	at clojure.lang.Compiler.analyze(Compiler.java:6657)

	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3835)

	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6921)

	at clojure.lang.Compiler.analyze(Compiler.java:6701)

	at clojure.lang.Compiler.access$300(Compiler.java:38)

	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6298)

	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6919)

	at clojure.lang.Compiler.analyze(Compiler.java:6701)

	at clojure.lang.Compiler.analyze(Compiler.java:6657)

	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6030)

	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5407)

	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3973)

	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6917)

	at clojure.lang.Compiler.analyze(Compiler.java:6701)

	at clojure.lang.Compiler.eval(Compiler.java:6975)

	at clojure.lang.Compiler.eval(Compiler.java:6968)

	at clojure.lang.Compiler.load(Compiler.java:7430)

	at clojure.lang.Compiler.loadFile(Compiler.java:7368)

	at clojure.main$load_script.invokeStatic(main.clj:277)

	at clojure.main$init_opt.invokeStatic(main.clj:279)

	at clojure.main$init_opt.invoke(main.clj:279)

	at clojure.main$initialize.invokeStatic(main.clj:310)

	at clojure.main$null_opt.invokeStatic(main.clj:344)

	at clojure.main$null_opt.invoke(main.clj:341)

	at clojure.main$main.invokeStatic(main.clj:423)

	at clojure.main$main.doInvoke(main.clj:386)

	at clojure.lang.RestFn.applyTo(RestFn.java:137)

	at clojure.lang.Var.applyTo(Var.java:700)

	at clojure.main.main(main.java:37)

Caused by: java.lang.RuntimeException: Unable to resolve var: cider.nrepl.middleware.macroexpand/wrap-macroexpand in this context

	at clojure.lang.Util.runtimeException(Util.java:221)

	at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:710)

	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6919)

	... 34 more

Subprocess failed
```

**Comment by luxbock** [comment]
Turns out this was due to a dependency in my `profiles.clj` pulling in an older version of `tools.reader` which in combination with CIDER and zprint caused the exception.

**Comment by luxbock** [comment]
Just wanted to let you know that `zprint` is truly a life saver when working with the informative but verbose error messages of `clojure.spec`. I use:
```clojure
(set! s/*explain-out*
      (fn [ex-data]
        (if ex-data
          (zprint ex-data)
          (println "Success!"))))
```
..and it works great!

**Comment by kkinnear** [comment]
Thanks for mentioning this.  I'm glad it helps!  I haven't gotten into `clojure.spec` enough to have that problem yet, though I expect to soon as I remove the schema support from the Clojurescript port of zprint.  I have spent some time getting zprint to format spec files so that they come out more or less like the ones for Clojure, for what that is worth.

I expect that zprint is alphabetically ordering the keys returned in the error map.  That is usually better than the random order they come out otherwise, but you can also order the keys the way that you want them.  For example `{:map {:key-order [:in :path]}}` will put `:in` first and `:path` second and then the other keys will be alphabetized.  Ordering them however you want might or might not help, but I wanted to mention it in case you didn't know about this capability.  For what it is worth, you can also get zprint to ignore keys (with or without telling you it did so), in case there is stuff that you don't want to see.  See `{:map {:key-ignore ...}}` and `{:map {:key-ignore-silent ...}}`.

Thanks again for bringing this up!

**Comment by luxbock** [comment]
Thanks, yeah I have read about these features from the README but haven't got to implementing any of them yet. I'm sure I will get to it later but I'm already quite pleased with spec output using the default `zprint` and I'm also using it for a pretty printing eval+replace via CIDER which is very handy.
