### ISSUE TITLE
Error when formatting source file containing `##NaN`, `##Inf` and `##-Inf`

### ISSUE THREAD

**Issue by RolT** [kkinnear/zprint#207]
Hello,

I'm having an issue when formatting source files containing either `##NaN`, `##Inf` or `##-Inf`.

```
Failed to format file: my_file.clj because java.lang.Exception: :reader-macro node expects 2 values. [at line 2, column 1]
	at rewrite_clj.reader$throw_reader.invokeStatic(reader.clj:18)
	at rewrite_clj.reader$throw_reader.doInvoke(reader.clj:11)
	at clojure.lang.RestFn.invoke(RestFn.java:490)
	at rewrite_clj.reader$read_n.invokeStatic(reader.clj:157)
	at rewrite_clj.reader$read_n.invoke(reader.clj:145)
	at rewrite_clj.parser.core$parse_printables.invokeStatic(core.clj:50)
	at rewrite_clj.parser.core$parse_printables.doInvoke(core.clj:46)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at rewrite_clj.parser.core$fn__2195.invokeStatic(core.clj:142)
	at rewrite_clj.parser.core$fn__2195.invoke(core.clj:111)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at rewrite_clj.reader$read_with_meta.invokeStatic(reader.clj:132)
	at rewrite_clj.reader$read_with_meta.invoke(reader.clj:128)
	at rewrite_clj.parser.core$parse_next.invokeStatic(core.clj:35)
	at rewrite_clj.parser.core$parse_next.invoke(core.clj:33)
	at rewrite_clj.reader$read_n.invokeStatic(reader.clj:153)
	at rewrite_clj.reader$read_n.invoke(reader.clj:145)
	at rewrite_clj.parser.core$parse_printables.invokeStatic(core.clj:50)
	at rewrite_clj.parser.core$parse_printables.doInvoke(core.clj:46)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at rewrite_clj.parser.core$fn__2195.invokeStatic(core.clj:142)
	at rewrite_clj.parser.core$fn__2195.invoke(core.clj:111)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at rewrite_clj.reader$read_with_meta.invokeStatic(reader.clj:132)
	at rewrite_clj.reader$read_with_meta.invoke(reader.clj:128)
	at rewrite_clj.parser.core$parse_next.invokeStatic(core.clj:35)
	at rewrite_clj.parser.core$parse_next.invoke(core.clj:33)
	at rewrite_clj.parser$parse.invokeStatic(parser.clj:13)
	at rewrite_clj.parser$parse.invoke(parser.clj:10)
	at rewrite_clj.parser$parse_all$fn__2218.invoke(parser.clj:18)
	at clojure.core$repeatedly$fn__6479.invoke(core.clj:5138)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5419.invokeStatic(core.clj:139)
	at clojure.core$take_while$fn__5935.invoke(core.clj:2908)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5419.invokeStatic(core.clj:139)
	at clojure.core$dorun.invokeStatic(core.clj:3121)
	at clojure.core$doall.invokeStatic(core.clj:3136)
	at clojure.core$doall.invoke(core.clj:3136)
	at rewrite_clj.parser$parse_all.invokeStatic(parser.clj:20)
	at rewrite_clj.parser$parse_all.invoke(parser.clj:15)
	at rewrite_clj.parser$parse_string_all.invokeStatic(parser.clj:35)
	at rewrite_clj.parser$parse_string_all.invoke(parser.clj:32)
	at zprint.core$zprint_file_str.invokeStatic(core.cljc:1292)
	at zprint.core$zprint_file_str.invoke(core.cljc:1218)
	at zprint.core$zprint_file_str.invokeStatic(core.cljc:1327)
	at zprint.core$zprint_file_str.invoke(core.cljc:1218)
	at zprint.main$_main$fn__12586.invoke(main.cljc:672)
	at zprint.main$_main.invokeStatic(main.cljc:672)
	at zprint.main$_main.doInvoke(main.cljc:302)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at zprint.main.main(Unknown Source)
```

This seems related to https://github.com/clj-commons/rewrite-clj/issues/75 which was fixed in  v1.0.572-alpha. Bumping the version to `[rewrite-clj "1.0.572-alpha"]` fixes the error for me, at least for java (I have not tried to compile with graalvm).

**Comment by kkinnear** [comment]
Yes, this is a duplicate of the zprint issue #153, the fix for which is a major component of the upcoming version `1.2.0`.  As you have figured out, it is fixed by using the new version of `rewrite-clj` -- thank you for figuring that out, and I'm sorry to had to go to the work to do so.  If you are using the zprint as a library, then you may have already fixed your problem.  The new version of `rewrtie-clj` was *mostly* a drop in replacement for the old version.

If you are using the pre-built binaries, there are several alpha versions of `1.2.0` [available here](https://github.com/kkinnear/zprint/releases/tag/1.2.0-alpha1).   The release is listed as `-alpha1`, but all of the alphas for `1.2.0` are in the same place. The original `-alpha1` version is available for both Mac and Linux, and an updated `-alpha2` version is available only for Linux.  The original `-alpha1` version fixed the `##NaN` problem, but had some issues where it changed the formatting of other things slightly (and slightly incorrectly).  The `-alpha2` version is better, but still has a small difference from `1.1.2` which it shouldn't have.  I have had to redesign a substantial piece of the new code in `1.2.0` (unrelated to moving to the new `rewrite-clj`) in order to resolve the problems that the alpha versions uncovered.  Which is why `1.2.0` isn't yet released.

If you want a pre-built binary and are using Linux, you could try out the `-alpha2` version and see if that will work for now.  The actual formatting changes between its output and the final `1.2.0` are extremely subtle and only show up in very unusual circumstances (i.e., with a very unusual configuration).  It should be fine for you.  

If you want a pre-built binary and are using a Mac, let me know, and I will drop an `-alpha3` into the alpha release in a day or so, and you can give that a try (which would be a small bit of work for me, but which would also give the latest code some additional testing, which would be a good thing too).

Thanks for your work on this issue!

**Comment by RolT** [comment]
Thanks, very responsive as always ! I'm on Linux, but can definitely test out a newer version you push some code or releases here. I'm closing this one then, since it's a duplicate. I guess searching for `#` characters in github doesn't work.
